### ISSUE TITLE
What version of C++ did u use for 4heat ?

### ISSUE THREAD

**Issue by catdogmaus** [leoshusar/4heat-esphome#11]
I did try to push 4heat together in one chip with ESPHome BT proxy but did land on some compiling errors like
 `src/esphome/components/fourheat/common.h:8:37: note: 'std::optional' is only available from C++17 onwards src/esphome/components/fourheat/common.h:8:37: error: 'optional' is not a member of 'std'` also some other similar.
there seems to be some C++ version problem
thanks

**Comment by leoshusar** [comment]
I'm not using any specific C++ version, everything just works for me. But I'm using ESP-IDF framework, so my idea is, maybe it uses C++17?

You can enable C++17 using build flags and it *should* work, something like this: 

```yaml
esphome:
  platformio_options:
    build_flags: "-std=gnu++17"
    build_unflags: "-std=gnu++11"
```

I found ESPHome has some custom `std::optional` reimplementation, but I don't know if it can do everything I need. When I have some time I might look into it.
