### ISSUE TITLE
mode switch 

### ISSUE THREAD

**Issue by catdogmaus** [leoshusar/4heat-esphome#9]
I hate to ask about the issue that might not be related to your code at all.
Is it possible to using yaml add the mode switch? I added lots of datapoints I needed but what I am trying to implement now is add night mode switch. What it should do is simply switch off cleaning engine and some other noisy stuff.
Basically what I have is 4-5 datapoints and turning the switch on should send all of them state 1 , turning switch off it should revert back to state 0.
Also it would be great to switch same time power from auto to some lower settings and afterwards back again. although the latter can probably be achieved somehow with the help of HA automations. However, this would add for users another layer of complexity, and doing it using yaml if possible would probably be more preferable.
Thanks

**Comment by leoshusar** [comment]
Hi, no worries, feel free to ask.

For the first case I'd just do a [template switch](https://esphome.io/components/switch/template.html). In the `turn_on_action` you can set all needed switches to your desired state, in the `turn_off_action` set them to the opposite.
You just need to figure out some `lambda` logic which decides if it's currently night mode or not. I can think of two ways - check some (or all) switches if they are on / off and decide on that, or create a binary_sensor template which will hold the value. Or you can use `assumed_state`, but this will create a switch made of two buttons ON and OFF instead of a normal indicative switch in HA.

```yaml
select:
  - id: power
    name: Výkon
    platform: fourheat
    datapoint: B20364
    options:
      1: "P1"
      2: "P2"
      3: "P3"
      4: "P4"
      5: "P5"
      6: "P6"
      7: "Auto"

# Example configuration entry
switch:
  - platform: template
    name: Night mode
    lambda: |-
      if (your logic to check if it's night mode) {
        return true; // it is night mode, switch indicates ON
      } else {
        return false; // else OFF
      }
    turn_on_action:
      - switch.turn_off: switch1
      - switch.turn_off: switch2
      - switch.turn_off: switch3
      - select.set:
          id: power
          option: "P2"
    turn_off_action:
      - switch.turn_on: switch1
      - switch.turn_on: switch2
      - switch.turn_on: switch3
      - select.set:
          id: power
          option: "Auto"
```
(YAML not tested, quickly wrote off the top of my head)

I have also included your power setting. You can also create text sensor template `previous_power`, which will hold the previous power setting, if you want to use not only `Auto`, but for example `P4, P5, P6, Auto` and always go back to the previous value.

I hope I understood you well.

**Comment by catdogmaus** [comment]
> For the first case I'd just do a [template switch](https://esphome.io/components/switch/template.html).

ESPHome is not really my topic. So I have first to create those 4 switches...
From Tiemme documentation I have datapoints that have default value 0. 
```
B20701  Cleaning Motor Off in Night Mode, 
B20700  Cleaning Motor 2 Off in Night Mode, 
B20699  Cleaning Motor 3 Off in Night Mode, 
B20698  Charging Motor Off in Night Mode
```
I am actually bit confused how to write yaml so that switch _on_ will send value 1 and switch _off_ will send 0.
I should probably use   `  on_turn_on:    on_turn_off: ` but what actual command it should be to send 1 and 0?

So something like this:
```
switch:
  - platform: fourheat
    id: ChargingMotorOffinNightMode
    name: Charging Motor Off in Night Mode
    internal
    on_turn_on:
    - # datapoint: B20698 some command to send 1
    on_turn_off:
    - # datapoint: B20698 some command to send 0
```

As I understand when I set those switches internal there will be no separate switches in frontend for the user to fiddle.
Ideally, as I imagine this, in front end there would only be a Nigth Mode switch, and HA automation/helper could then turn it on according to the time of day. 
I also imagine that this timer can be ultimately set using ESPHome, but it's definitely too much for me if I can't even get my simple switches in place.

**Comment by leoshusar** [comment]
Can you send me the documentation? By the `Cleaning Motor Off in Night Mode` it seems to me like the Tiemme itself supports some kind of night mode, maybe it could be enabled directly without needing to mess with individual switches?

Anyway yeah, you create four switches like this:
```yaml
switch:
  - platform: fourheat
    id: charging_motor_off
    datapoint: B20698
    on_data: '1'
    off_data: '0'
    parser: return data[data.size() - 1] != '0';

  - platform: fourheat
    id: another_switch
    datapoint: B12345
    on_data: '1'
    off_data: '0'
    parser: return data[data.size() - 1] != '0';
```

The first switch: it sends an empty command to `A20698` and Tiemme should respond `B20698000000000001` if ON. This is how it *usually* works, by sending the data to A.
The `parser` part then checks the last character in the response - if it's not `'0'`, the switch is ON.
*If* the response is different, for example the `1` is not last, but third last like this `B20698000000000100`, you write the parser like this: `return data[data.size() - 3] != '0';`. Hope this makes sense.

If you don't specify `name`, it's considered an `internal` component and won't be visible to HA, it will only be used internally for your template switch.

And then you control them like this using their `id`:
```yaml
switch:
  - platform: template
    ...
    turn_on_action:
      - switch.turn_off: charging_motor_off
      - switch.turn_off: another_switch
    turn_off_action:
      - switch.turn_on: charging_motor_off
      - switch.turn_on: another_switch
```
